### ISSUE TITLE
Ractive-Ractive leaks child instance's properties

### ISSUE THREAD

**Issue by ElliotChong** [rstacruz/ractive-ractive#1]
While working with Ractive-Ractive I've noticed that the child Ractive's instance properties get exposed to the parent when using the parent's `get` and `set` methods.

When doing something like `parent.get("child.template");` instead of accessing `child` as if it was doing a `child.get("template");` it's actually just returning `child.template`.

I first noticed this was happening when my child instance had a `data` property defined within its `data` configuration (i.e.: `child.get("data");` - it's setup this way to match an external data source) and was receiving errors about Ractive trying to overwrite the `data` property when no setter was present (due to `ractive.data` now being inaccessible in Ractive v0.7.x), aka: it was trying to modify `child.data` directly rather than `child.set("data", ...)`.

I'll take a crack at seeing if there's a way to proxy directly to the child's data; however, I figured I'd ask for any advice / suggestions for this as a first step. Thanks for Ractive-Ractive! :)

**Comment by rstacruz** [comment]
a fix is welcome :)

**Comment by rstacruz** [comment]
unfortunately this is actually intended behavior.

``` js
var view = new Ractive({
  data: {
    user: { name: "John" } }
  }
});

view.get('user.name') //=> "John"
```

ractive-ractive is simply making this expected behavior work, but with Ractive instances instead of Objects.

**Comment by rstacruz** [comment]
oh wait, oops... misread. haha. please do help fix it. IIRC i actually implemented that but maybe it broke.

**Comment by rstacruz** [comment]
semi-relevant: https://github.com/rstacruz/ractive-ractive/blob/master/test/test.js#L188-L192

**Comment by ElliotChong** [comment]
I think I've worked up a solution, will submit a pull request in a bit! :+1:

**Comment by ElliotChong** [comment]
@rstacruz I did some heavy lifting in #2 but I think it makes Ractive-Ractive a lot more predictable on the whole. Let me know what you think!
